// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_5PG8H7spwPZDM3bwzinyhfFrk_UFrlk',
    appId: '1:588693971661:web:873d7b83185b5862adbf84',
    messagingSenderId: '588693971661',
    projectId: 'fruitopia-flutter',
    authDomain: 'fruitopia-flutter.firebaseapp.com',
    storageBucket: 'fruitopia-flutter.firebasestorage.app',
    measurementId: 'G-YR19RSJFPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzUySh2Lb3wiKVgMH8bl-97z_ZE6JUKoc',
    appId: '1:588693971661:android:c1875556d9505227adbf84',
    messagingSenderId: '588693971661',
    projectId: 'fruitopia-flutter',
    storageBucket: 'fruitopia-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf_oaFdPs87RkKsNnYK8gVifFeTw6Xa3U',
    appId: '1:588693971661:ios:8b13651ec9b1266fadbf84',
    messagingSenderId: '588693971661',
    projectId: 'fruitopia-flutter',
    storageBucket: 'fruitopia-flutter.firebasestorage.app',
    iosBundleId: 'com.example.fruitopia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf_oaFdPs87RkKsNnYK8gVifFeTw6Xa3U',
    appId: '1:588693971661:ios:8b13651ec9b1266fadbf84',
    messagingSenderId: '588693971661',
    projectId: 'fruitopia-flutter',
    storageBucket: 'fruitopia-flutter.firebasestorage.app',
    iosBundleId: 'com.example.fruitopia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_5PG8H7spwPZDM3bwzinyhfFrk_UFrlk',
    appId: '1:588693971661:web:ed05d14f73b3ac0aadbf84',
    messagingSenderId: '588693971661',
    projectId: 'fruitopia-flutter',
    authDomain: 'fruitopia-flutter.firebaseapp.com',
    storageBucket: 'fruitopia-flutter.firebasestorage.app',
    measurementId: 'G-HNTB0X39Y9',
  );
}
